### ISSUE TITLE
no-extra element for separator

### ISSUE THREAD

**Issue by linkstrifer** [jobana/ejercicios-bootcamp-html-css#3]
Puedes usar un `::after` para esto, te ahorras un elemento y tiene el mismo efecto:

https://github.com/jobana/ejercicios-bootcamp-html-css/blob/efbb42bb02d4afa7ba3731691cac3a99fcfe4ed1/html-css-bootcamp/flexbox/exercise-1%20other%20way/exercise1-otherway.css#L112-L117

usando `after`:

```css
date::after { 
     display: block;
     content: '';
     margin-top: 20px; 
     height: 4px; 
     border-top: 1px solid #c9c6c6; 
     border-bottom: 1px solid #c9c6c6; 
 } 
```
